[options]

; Database connection
db_host = localhost
db_port = 5432
db_user = odoouser
db_password = odoouser
db_name = hoteldata

; Server port
http_port = 8070

; Admin password
admin_passwd = admin

; Disable demo data
without_demo = True

; Logging
;logfile = /var/log/odoo/odoo19.log

; Addon paths (absolute)
addons_path = C:/Users/alfer/OneDrive/Desktop/odoo/OdooHotel/odoo-19.0/addons,C:/Users/alfer/OneDrive/Desktop/odoo/OdooHotel/odoo-19.0/odoo/addons,C:/Users/alfer/OneDrive/Desktop/odoo/OdooHotel/odoo-19.0/mukwebthemeaddon,C:/Users/alfer/OneDrive/Desktop/odoo/OdooHotel/odoo-19.0/myaddons

; wkhtmltopdf for PDF reports
wkhtmltopdf = /usr/local/bin/wkhtmltopdf
